PinkGarage/Models/ParkedVehicle.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PinkGarage.Models {

    public class ParkedVehicle {

        public int ID { get; set; }

        [Required]
        [MinLength(6)]
        [MaxLength(20)]
        public string RegNum { get; set; }

        public Type Type { get; set; }

        [Display(Name = "FuelType")]
        public EngineTypes EngineType { get; set; }


        [Display(Name = "Color")]
        [MaxLength(20)]
        public string Color { get; set; }

        [Display(Name = "Brand")]
        [MaxLength (20)]
        [Required]
        public string Brand { get; set; }


        [Display(Name = "Model")]
        [MaxLength(20)]
        [Required]
        public string Model { get; set; }

        [Range(1, 10)]
        [Required]
        public int NumOfWheels { get; set; }

        public DateTime CheckInTime { get; set; }

    }
    public enum Type {
        Car,
        Bus,
        MotorCycle
    }

    public enum EngineTypes
    {
        Petrol,
        Diesel,
        Electric,
        Gas,
        Hybrid
    }


}

PinkGarage/Controllers/ParkedVehiclesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PinkGarage.Models;

namespace PinkGarage.Controllers {
    public class ParkedVehiclesController : Controller {
        private GarageDbContext db = new GarageDbContext();

        //// GET: ParkedVehicles
        //public ActionResult Index()
        //{
        //    return View(db.ParkedVehicles.ToList());
        //}


        // GET: ParkedVehicles // adding Sorting Functionality
        public ActionResult Index(string orderBy, string searchString) {
            ViewBag.Error = "";
            ViewBag.SortByRegNum = orderBy == "RegNum" ? "RegNum_desc" : "RegNum";
            ViewBag.SortByType = orderBy == "Type" ? "Type_desc" : "Type";
            ViewBag.SortByColor = orderBy == "Color" ? "Color_desc" : "Color";
            ViewBag.SortByBrand = orderBy == "Brand" ? "Brand_desc" : "Brand";
            ViewBag.SortByCheckIn = orderBy == "CheckInTime" ? "CheckInTime_desc" : "CheckInTime";

            var vehicles = db.ParkedVehicles.Select(p => p);

            //search by RegNum 
            if(!String.IsNullOrEmpty(searchString)) {
                vehicles = vehicles.Where(p => p.RegNum.Equals(searchString));
                if(vehicles.Count() == 0)
                    ViewBag.Error = "Sorry!!! No Vehicle with the Registration Number : " + searchString + " is currentely checkin";
                //ModelState.AddModelError("", "");

            }


            switch(orderBy) {
                case "RegNum":
                    vehicles = vehicles.OrderBy(p => p.RegNum);
                    break;
                // the default sort order is ascending
                case "RegNum_desc":
                    vehicles = vehicles.OrderByDescending(p => p.RegNum);
                    break;
                case "Type":
                    vehicles = vehicles.OrderBy(p => p.Type);
                    break;
                case "Type_desc":
                    vehicles = vehicles.OrderByDescending(p => p.Type);
                    break;

                case "Color":
                    vehicles = vehicles.OrderBy(p => p.Color);
                    break;
                case "Color_desc":
                    vehicles = vehicles.OrderByDescending(p => p.Color);
                    break;

                case "Brand":
                    vehicles = vehicles.OrderBy(p => p.Brand);
                    break;
                case "Brand_desc":
                    vehicles = vehicles.OrderByDescending(p => p.Brand);
                    break;
                case "CheckInTime":
                    vehicles = vehicles.OrderBy(p => p.CheckInTime);
                    break;
                case "CheckInTime_desc":
                    vehicles = vehicles.OrderByDescending(p => p.CheckInTime);
                    break;

                default:
                    break;
            }

            return View(vehicles.ToList());
        }
        

        
        // GET: ParkedVehicles/Details/5
        public ActionResult Details(int? id, string time) {
            if(id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if(parkedVehicle == null) {
                return HttpNotFound();
            }
            ViewBag.Parkedtime = time;
            return View(parkedVehicle);
        }

        // GET: ParkedVehicles/checkout
        public ActionResult Receipt(int? id) {
            if(id == null) {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if(parkedVehicle == null) {
                return HttpNotFound();
            }
            db.ParkedVehicles.Remove(parkedVehicle);
            db.SaveChanges();

            return View(parkedVehicle);
        }

        // POST: ParkedVehicles/Receipt
        [HttpPost, ActionName("Receipt")]
        [ValidateAntiForgeryToken]
        public ActionResult ReceiptConfirmed(int id) {
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            db.ParkedVehicles.Remove(parkedVehicle);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: ParkedVehicles/Checkin
        public ActionResult Checkin() {
            return View();
        }

        // POST: ParkedVehicles/Checkin
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkin([Bind(Include = "ID,RegNum,Type,EngineType, Color,Brand,Model,NumOfWheels")] ParkedVehicle parkedVehicle) {
            var vehicles = db.ParkedVehicles.Select(p => p);

            vehicles = vehicles.Where(p => p.RegNum.Equals(parkedVehicle.RegNum));
            if(vehicles.Count() > 0) {
                ModelState.AddModelError("RegNum", "A vehicle with same registration number already exists in the garage. Try with another one!");
            }

            if(ModelState.IsValid) {
                parkedVehicle.CheckInTime = DateTime.Now;
                db.ParkedVehicles.Add(parkedVehicle);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(parkedVehicle);
        }

        public ActionResult Checkout(string regnum)
        {
            ViewBag.Error = "";
            ViewBag.VehicleRegNum = regnum;
            var model = db.ParkedVehicles.Where(i => i.RegNum == regnum);
            if (!String.IsNullOrEmpty(regnum))
            {
                if (model.Count() == 0)
                {
                    ViewBag.Error = "Sorry!!! No Vehicle with the Registration Number : " + regnum + " is currentely checkin";
                    ViewBag.VehicleRegNum = "";
                }
            }
                         
            return View(model.ToList());
        }




        // GET: Employees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ParkedVehicle parkedVehicle = db.ParkedVehicles.Find(id);
            if (parkedVehicle == null)
            {
                return HttpNotFound();
            }
            return View(parkedVehicle);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,RegNum,Type,EngineType, Color,Brand,Model,NumOfWheels,CheckInTime")] ParkedVehicle parkedVehicle)
        {
            if (ModelState.IsValid)
            {
                db.Entry(parkedVehicle).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(parkedVehicle);
        }

        public ActionResult SearchVehicle(int? value, string SearchString)
        {
            IQueryable<ParkedVehicle> model;
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "Registration Number", Value = "1"});
            items.Add(new SelectListItem { Text = "Type", Value = "2" });
            items.Add(new SelectListItem { Text = "Color", Value = "3"});
            items.Add(new SelectListItem { Text = "Brand", Value = "4" });
            ViewBag.PropertySelect = items;
            model = db.ParkedVehicles.Where(i => i.ID == 0);
            switch (value)
            {
                case 1:
                    model = db.ParkedVehicles.Where(i => i.RegNum == SearchString);
                    break;
                case 2:
                    model = db.ParkedVehicles.Where(i => i.Type.ToString() == SearchString);
                    break;
                case 3:
                    model = db.ParkedVehicles.Where(i => i.Color == SearchString);
                    break;
                case 4:
                    model = db.ParkedVehicles.Where(i => i.Brand == SearchString);
                    break;
                default:
                    break;
            }
            return View(model.ToList());
        }


        protected override void Dispose(bool disposing) {
            if(disposing) {

                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PinkGarage/Views/ParkedVehicles/Checkin.cshtml
@model PinkGarage.Models.ParkedVehicle

@{
    ViewBag.Title = "Vehicles Checkin";
}

<h3 class="pinkheader">@ViewBag.Title</h3>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
      
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EngineType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.EngineType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EngineType, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfWheels, new { htmlAttributes = new { @min = 1, @max = 10, @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfWheels, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CheckInTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckInTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckInTime, "", new { @class = "text-danger" })
            </div>
        </div>*@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Checkin" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div><span class="searchlistbutton">
    @Html.ActionLink("Back to List", "Index")</span>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PinkGarage/Views/ParkedVehicles/Checkout.cshtml
@model IEnumerable<PinkGarage.Models.ParkedVehicle>

@{
    ViewBag.Title = "Checkout";
}
<h3 class="pinkheader">@ViewBag.Title</h3>

@using (Html.BeginForm())
{
    <p>
        Registration number: @Html.TextBox("regnum")
        <input type="submit" value="Fetch Details" />
    </p>
}

<p>
    @ViewBag.Error
</p>

<hr />
<h4><i>Details of the Vehicle @ViewBag.VehicleRegNum</i></h4>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EngineType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumOfWheels)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RegNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EngineType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumOfWheels)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckInTime)
        </td>
        <td>
            @Html.ActionLink("Check Out", "Receipt", new { id = item.ID })
        </td>
    </tr>
}

</table>

PinkGarage/Views/ParkedVehicles/Create.cshtml
@model PinkGarage.Models.ParkedVehicle

@{
    ViewBag.Title = "Check in";
}

<h2>Check in Vehicle in Pinkgarage</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Enter the details of the vehicle to be parked in the garage</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.RegNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RegNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RegNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Type, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EngineType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.EngineType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EngineType, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Color, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Color, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Color, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Brand, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Brand, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Brand, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Model, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Model, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Model, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumOfWheels, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumOfWheels, new { htmlAttributes = new { @min = 1, @max = 10, @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumOfWheels, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.CheckInTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CheckInTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CheckInTime, "", new { @class = "text-danger" })
            </div>
        </div>*@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Checkin" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PinkGarage/Views/ParkedVehicles/Details.cshtml
@model PinkGarage.Models.ParkedVehicle

@{
    ViewBag.Title = "Vehicle Details";
}

<div>
    <h4>ParkedVehicle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RegNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RegNum)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EngineType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EngineType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Color)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Color)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Brand)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Brand)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Model)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Model)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumOfWheels)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumOfWheels)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CheckInTime)
        </dd>
        <dt>
           Parked Time
        </dt>

        <dd>
           @ViewBag.Parkedtime
        </dd>
       
    </dl>
</div>
<p>
    <span class="searchlistbutton">
        @Html.ActionLink("Check Out", "Receipt", new { id = Model.ID })</span>
    <span class="searchlistbutton"> @Html.ActionLink("Back to List", "Index")</span>
</p>

PinkGarage/Views/ParkedVehicles/FilterObject.cshtml
@model IEnumerable<PinkGarage.Models.ParkedVehicle>

@{
    ViewBag.Title = "FilterObject";
}

<h3 class="pinkheader">Filter the Object for search</h3>




@using (Html.BeginForm("FilterObject", "ParkedVehicles", FormMethod.Post))
{
    <p>
        Enter Car's Brand: @Html.TextBox("brand")
        @{var type = Model.ToList()[0].Type;}
        Choose VehicleType: @Html.EnumDropDownListFor(model => type)
        <input type="submit" value="Filter" />

    </p>
}




<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegNum)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EngineType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Model)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NumOfWheels)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckInTime)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.RegNum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Type)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EngineType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Color)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Brand)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Model)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NumOfWheels)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CheckInTime)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.ID }) 
           
        </td>
    </tr>
}

</table>

PinkGarage/Views/ParkedVehicles/Index.cshtml
@model IEnumerable<PinkGarage.Models.ParkedVehicle>

@{
    ViewBag.Title = "Vehicles - Checkout";
}

<h3 class="pinkheader">@ViewBag.Title</h3>

<h3><i>@ViewBag.Message</i></h3>

<h3 class="pinkheader"></h3>
<hr />

@using(Html.BeginForm()) {
    <div class="IndexSearch">
        <p>
            Registration Number : @Html.TextBox("SearchString")
            <input type="submit" value="search" />
        </p>
        <div class="searchlist">
            @Html.ActionLink("Show All", "Index")
        </div>
    </div>

      
}

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.RegNum)
            <a href="@Url.Action("Index", "ParkedVehicles", new {orderBy = ViewBag.SortByRegNum })">
                <img src="~/Image/up_downArrow1.png" />
            </a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Type)
            <a href="@Url.Action("Index", "ParkedVehicles", new {orderBy = ViewBag.SortByType })">
                <img src="~/Image/up_downArrow1.png" />
            </a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Color)
            <a href="@Url.Action("Index", "ParkedVehicles", new {orderBy = ViewBag.SortByColor })">
                <img src="~/Image/up_downArrow1.png" />
            </a>

        </th>
        <th>
            @Html.DisplayNameFor(model => model.Brand)
            <a href="@Url.Action("Index", "ParkedVehicles", new {orderBy = ViewBag.SortByBrand })">
                <img src="~/Image/up_downArrow1.png" />
            </a>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CheckInTime)
            <a href="@Url.Action("Index", "ParkedVehicles", new {orderBy = ViewBag.SortByCheckIn })">
                <img src="~/Image/up_downArrow1.png" />
            </a>
        </th>
        <th>
            Time Parked <br /> HH:MM
        </th>
        <th></th>
    </tr>

    <p>
        @ViewBag.Error
    </p> 

    @foreach(var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.RegNum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Type)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Color)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Brand)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CheckInTime)
            </td>
            <td>
                @{
                    System.TimeSpan a = DateTime.Now.Subtract(item.CheckInTime);
                    <div>@Math.Floor(a.TotalHours) : @a.ToString("mm")</div>
                    string timestring;
                    string HourString;
                    string MinString;
                    if(Math.Floor(a.TotalHours) <= 1) { HourString = " Hr : "; } else { HourString = " Hrs : "; }

                    if(a.Minutes <= 1) { MinString = "Min"; } else { MinString = "Mins"; }
                    timestring = @Math.Floor(a.TotalHours) + HourString + @a.ToString("mm") + MinString;

                }
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID, time = timestring }) |
                @*@Html.ActionLink("Edit", "Edit", new { id = item.ID}) |*@
                @Html.ActionLink("Checkout", "Receipt", new { id = item.ID })
            </td>
        </tr>

                    }

</table>